workflows:
  hilbu_release:
    name: HILBU • Android AAB + iOS TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      groups:
        - hilbu_android
        - hilbu_apple
      vars:
        EXPO_NO_TELEMETRY: "1"
        NODE_OPTIONS: "--max_old_space_size=4096"
        CI: "1"   # make expo non-interactive

    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Use Java 17
        script: |
          echo 'export JAVA_HOME=$(/usr/libexec/java_home -v 17)' >> $CM_ENV
          java -version

      - name: Install Node deps
        script: npm ci

      - name: Ensure Expo CLI
        script: npx --yes expo --version

      - name: Resolve bundle identifiers from Expo config
        script: |
          INFO=$(npx expo config --json)
          IOS_BUNDLE_ID=$(echo "$INFO" | python3 -c 'import sys,json; d=json.load(sys.stdin); print((d.get("ios") or {}).get("bundleIdentifier",""))')
          ANDROID_APP_ID=$(echo "$INFO" | python3 -c 'import sys,json; d=json.load(sys.stdin); print((d.get("android") or {}).get("package",""))')
          if [ -z "$IOS_BUNDLE_ID" ] || [ -z "$ANDROID_APP_ID" ]; then
            echo "Failed to resolve bundle identifiers from Expo config"; exit 1
          fi
          echo "IOS_BUNDLE_ID=$IOS_BUNDLE_ID" >> $CM_ENV
          echo "ANDROID_APP_ID=$ANDROID_APP_ID" >> $CM_ENV
          echo "Resolved iOS: $IOS_BUNDLE_ID, Android: $ANDROID_APP_ID"

      - name: Prebuild (force-generate ios/ and android/)
        script: |
          set -e
          echo "== Primary attempt: expo prebuild ios,android =="
          npx expo prebuild --platform ios,android --clean || true

          echo "== Verify and fallback if needed =="
          if [ ! -d ios ]; then
            echo "ios/ missing -> fallback: npx expo run:ios --no-install"
            npx expo run:ios --no-install || true
          fi
          if [ ! -d android ]; then
            echo "android/ missing -> fallback: npx expo run:android --no-install"
            npx expo run:android --no-install || true
          fi

          echo "== Final check =="
          ls -la
          [ -d ios ] || { echo "❌ ios/ still missing after fallback"; exit 1; }
          [ -d android ] || { echo "❌ android/ still missing after fallback"; exit 1; }
          echo "✅ ios/ and android/ exist"

      - name: 🔢 Automatic Version Bumping (Android versionCode & iOS buildNumber)
        script: |
          BN="${BUILD_NUMBER:-0}"
          if [ "$BN" = "0" ] || ! echo "$BN" | grep -Eq '^[0-9]+$'; then
            BN=$(date +%s | tail -c 7)
          fi
          echo "Using build number: $BN"

          # Android versionCode
          if [ -f android/app/build.gradle ]; then
            sed -i '' -E "s/(versionCode\s+)[0-9]+/\1${BN}/" android/app/build.gradle
          elif [ -f android/app/build.gradle.kts ]; then
            sed -i '' -E "s/(versionCode\s*\()\s*[0-9]+(\))/\1${BN}\2/" android/app/build.gradle.kts
          fi

          # iOS CFBundleVersion
          for P in $(find ios -name "Info.plist"); do
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BN" "$P" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BN" "$P"
          done

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: ✅ Quick env names (sanity check)
        script: |
          echo "Expecting ANDROID_KEYSTORE_BASE64, ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD"
          env | cut -d= -f1 | grep -E '^ANDROID_' || echo "(no ANDROID_* envs)"

      - name: Android | Decode keystore (supports Base64 OR file-var)
        script: |
          set -e
          mkdir -p android
          OUT="android/hilbu-upload.keystore"
          if [ -n "${ANDROID_KEYSTORE_BASE64:-}" ]; then
            echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$OUT" || { echo "Base64 decode failed"; exit 1; }
          elif [ -n "${ANDROID_KEYSTORE:-}" ] && [ -f "$ANDROID_KEYSTORE" ]; then
            cp "$ANDROID_KEYSTORE" "$OUT"
          else
            echo "ERROR: Neither ANDROID_KEYSTORE_BASE64 nor ANDROID_KEYSTORE (file var) is available."; exit 1
          fi
          [ -s "$OUT" ] || { echo "ERROR: Keystore file is empty"; exit 1; }
          ls -lh "$OUT"

      - name: Android | Build signed AAB (bundleRelease)
        script: |
          cd android
          ./gradlew clean bundleRelease \
            -Pandroid.injected.signing.store.file="$CM_BUILD_DIR/android/hilbu-upload.keystore" \
            -Pandroid.injected.signing.store.password="$ANDROID_KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$ANDROID_KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$ANDROID_KEY_PASSWORD" \
            --no-daemon --stacktrace
          cd ..

      - name: iOS | Fetch signing files and set profiles
        script: |
          app-store-connect fetch-signing-files \
            --issuer-id "$APPLE_API_ISSUER_ID" \
            --key-id "$APPLE_API_KEY_ID" \
            --private-key "$APP_STORE_PRIVATE_KEY" \
            --type IOS_APP_STORE "$IOS_BUNDLE_ID" --create
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: iOS | Build IPA (robust workspace & scheme pick)
        script: |
          set -e
          set -o pipefail
          # Find a real .xcworkspace directory (not its internal files)
          WS=$(find ios -maxdepth 1 -type d -name "*.xcworkspace" | head -n1)
          if [ -z "$WS" ]; then
            echo "No .xcworkspace found, listing ios/:"; ls -la ios; exit 1
          fi
          echo "Workspace: $WS"
          # List schemes safely
          SCHEMES=$(xcodebuild -list -json -workspace "$WS" | python3 -c 'import sys,json; d=json.load(sys.stdin); print("\n".join((d.get("workspace") or {}).get("schemes",[])))' || true)
          if [ -z "$SCHEMES" ]; then
            echo "Could not read schemes from workspace JSON; raw list:" 
            xcodebuild -list -workspace "$WS" || true
          else
            echo "Found schemes:"; echo "$SCHEMES"
          fi
          # Pick the first app scheme (skip Pods/tests/boost)
          PICK=""
          for S in $SCHEMES; do
            case "$S" in
              Pods-*|*Tests|*UITests|boost) continue ;;
            esac
            echo "Testing scheme: $S"
            if xcodebuild -showBuildSettings -workspace "$WS" -scheme "$S" | grep -q "WRAPPER_EXTENSION = app"; then
              PICK="$S"; break
            fi
          done
          if [ -z "$PICK" ]; then
            echo "Could not find an app scheme among: $SCHEMES"
            exit 1
          fi
          echo "Using app scheme: $PICK"
          xcode-project build-ipa --workspace "$WS" --scheme "$PICK" --archive-method app-store --verbose

    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_PRIVATE_KEY
        key_id: $APPLE_API_KEY_ID
        issuer_id: $APPLE_API_ISSUER_ID
        submit_to_testflight: true
