# HILBU (Expo) — Codemagic CI/CD
# Builds Android .aab and iOS .ipa
# Bundle IDs: com.hilbu.recovery (Android + iOS)

workflows:
  android_release:
    name: HILBU • Android Release (.aab)
    max_build_duration: 60
    environment:
      node: 18.20.4
      java: 17
      vars:
        APPLICATION_ID_ANDROID: com.hilbu.recovery
      android_signing:
        keystore:
          file: ANDROID_KEYSTORE
          password: $ANDROID_KEYSTORE_PASSWORD
          alias: $ANDROID_KEY_ALIAS
          key_password: $ANDROID_KEY_PASSWORD
    triggering:
      events: [ push ]
      branch_patterns:
        - pattern: main
          include: true
          source: true
    cache:
      cache_paths:
        - $HOME/.npm
        - ~/.gradle
        - android/.gradle
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Generate native projects if missing (Expo prebuild)
        script: |
          if [ ! -d "android" ] || [ ! -d "ios" ]; then
            npx expo prebuild --non-interactive --platform android,ios
          fi
      - name: Build Android App Bundle (release)
        script: |
          cd android
          ./gradlew clean bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/mapping/release/mapping.txt

  ios_release:
    name: HILBU • iOS Release (TestFlight/.ipa)
    max_build_duration: 90
    environment:
      node: 18.20.4
      xcode: 15.4
      cocoapods: default
      ios_signing:
        distribution_type: app-store
        app_store_connect_api_key:
          api_key: APP_STORE_CONNECT_API_KEY
          key_id: $APPLE_API_KEY_ID
          issuer_id: $APPLE_API_ISSUER_ID
      vars:
        BUNDLE_ID_IOS: com.hilbu.recovery
    triggering:
      events: [ push ]
      branch_patterns:
        - pattern: main
          include: true
          source: true
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/Library/Caches/CocoaPods
        - $HOME/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Generate iOS project if missing (Expo prebuild)
        script: |
          if [ ! -d "ios" ]; then
            npx expo prebuild --non-interactive --platform ios
          fi
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
      - name: Xcode archive (Release)
        script: |
          cd ios
          WORKSPACE=$(ls *.xcworkspace | head -n1)
          SCHEME=$(ls *.xcodeproj | head -n1 | sed 's/.xcodeproj//')
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/HILBU.xcarchive \
            clean archive \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID_IOS \
            CODE_SIGN_STYLE=Automatic \
            | xcpretty
      - name: Export .ipa for App Store
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/HILBU.xcarchive \
            -exportOptionsPlist <(printf '%s' '
              {
                "method": "app-store",
                "uploadSymbols": true,
                "compileBitcode": false
              }') \
            -exportPath $CM_BUILD_DIR/build/export \
            | xcpretty
    artifacts:
      - build/export/*.ipa
      - build/HILBU.xcarchive/dSYMs/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: APP_STORE_CONNECT_API_KEY
        key_id: $APPLE_API_KEY_ID
        issuer_id: $APPLE_API_ISSUER_ID
        submit_to_testflight: true
